// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8pU_n0h6LXdzD4UJhu-EKJpIER6y9a8',
    appId: '1:801503442154:web:277239f420ed2e2f5ad393',
    messagingSenderId: '801503442154',
    projectId: 'figuritas-app-a352b',
    authDomain: 'figuritas-app-a352b.firebaseapp.com',
    storageBucket: 'figuritas-app-a352b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Wyf7Lm5Fhffxs72WjtjRQsUgCMaQamg',
    appId: '1:801503442154:android:1e1b1732d30828f45ad393',
    messagingSenderId: '801503442154',
    projectId: 'figuritas-app-a352b',
    storageBucket: 'figuritas-app-a352b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5meBkaJlCZ7C2V9nzCdHq37Qf_iyrYEw',
    appId: '1:801503442154:ios:49dab54356b1a39e5ad393',
    messagingSenderId: '801503442154',
    projectId: 'figuritas-app-a352b',
    storageBucket: 'figuritas-app-a352b.firebasestorage.app',
    iosClientId:
        '801503442154-8r6at0vbunsvkf0r9vk5pudp394ddbm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.figugol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5meBkaJlCZ7C2V9nzCdHq37Qf_iyrYEw',
    appId: '1:801503442154:ios:49dab54356b1a39e5ad393',
    messagingSenderId: '801503442154',
    projectId: 'figuritas-app-a352b',
    storageBucket: 'figuritas-app-a352b.firebasestorage.app',
    iosClientId:
        '801503442154-8r6at0vbunsvkf0r9vk5pudp394ddbm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.figugol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb8pU_n0h6LXdzD4UJhu-EKJpIER6y9a8',
    appId: '1:801503442154:web:4c9faef8b6aaf7625ad393',
    messagingSenderId: '801503442154',
    projectId: 'figuritas-app-a352b',
    authDomain: 'figuritas-app-a352b.firebaseapp.com',
    storageBucket: 'figuritas-app-a352b.firebasestorage.app',
  );
}
